services:
  reportservice:
    image: reportservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

  db:
    image: postgres:17
    container_name: my_postgres
    environment:
      POSTGRES_DB: finom-report-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"